disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - nesting
  - blanket_disable_command
  - void_function_in_ternary
line_length:
 warning: 300
 error: 500
file_length:
  warning: 500
  error: 800
type_body_length:
  warning: 300
  error: 500
cyclomatic_complexity:
 warning: 12
 error: 15
function_body_length:
  warning: 100
  error: 200
